// Shared board query definitions — the 'calculator' engine behind
// both the classic dashboard's custom widgets and the smart grid board.
// Every board: which table, filterable fields, group-by, chart, sort,
// display columns, and numeric aggregations.

export const BOARD_OPTIONS = [
  {
    id:'contacts', label:'Contacts', icon:'👤', table:'contacts',
    statusField:'status', nameField:'first_name', subField:'source', valueField:null,
    dateField:'created_at',
    groupByOptions:['status','source','type','buyer_type','language'],
    statusOptions:['New','Hot','Warm','Cold','Active','Nurturing','Past Client','Unresponsive','Do Not Contact'],
    extraFilters:[{field:'source',label:'Source'},{field:'type',label:'Type'},{field:'buyer_type',label:'Buyer Type'}],
    sortOptions:[{field:'created_at',label:'Newest'},{field:'updated_at',label:'Last Updated'},{field:'first_name',label:'Name A-Z'}],
    displayCols:[
      {field:'first_name',label:'Name'},{field:'phone',label:'Phone'},{field:'email',label:'Email'},
      {field:'status',label:'Status'},{field:'source',label:'Source'},{field:'type',label:'Type'},
      {field:'buyer_type',label:'Buyer Type'},{field:'language',label:'Language'},
      {field:'created_at',label:'Date Added'},{field:'agent_id',label:'Agent'},
    ],
    chartFields:[{field:'status',label:'By Status'},{field:'source',label:'By Source'},{field:'buyer_type',label:'By Buyer Type'}],
    numericFields:[],
  },
  {
    id:'deals', label:'Production / Deals', icon:'💼', table:'deals',
    statusField:'stage', nameField:'addr', subField:'client_name', valueField:'gci',
    dateField:'ao_date',
    groupByOptions:['stage','side','sale_type','agent_id'],
    statusOptions:['Negotiations','Offer Accapted','Under Shtar','Under Contract','Closed','Deal Fell Through'],
    extraFilters:[{field:'side',label:'Side'},{field:'sale_type',label:'Sale Type'},{field:'agent_id',label:'Agent'}],
    sortOptions:[{field:'ao_date',label:'A/O Date'},{field:'close_date',label:'Close Date'},{field:'gci',label:'GCI High-Low'},{field:'created_at',label:'Newest'}],
    displayCols:[
      {field:'addr',label:'Address'},{field:'stage',label:'Stage'},{field:'side',label:'Side'},
      {field:'gci',label:'GCI'},{field:'production',label:'Production'},{field:'ao_date',label:'A/O Date'},
      {field:'close_date',label:'Close Date'},{field:'expected_close_date',label:'Expected Close'},
      {field:'client_name',label:'Client'},{field:'client_legal_name',label:'Legal Name'},
      {field:'sale_type',label:'Sale Type'},{field:'deal_type',label:'Deal Type'},
      {field:'status',label:'Status'},{field:'mls_number',label:'MLS#'},
      {field:'list_price',label:'List Price'},{field:'sale_price',label:'Sale Price'},
      {field:'agent_commission',label:'Agent Commission'},{field:'agent_id',label:'Agent'},
      {field:'notes',label:'Notes'},
    ],
    chartFields:[{field:'stage',label:'By Stage'},{field:'side',label:'By Side'},{field:'sale_type',label:'By Type'},{field:'agent_id',label:'By Agent'}],
    numericFields:[{field:'gci',label:'Total GCI'},{field:'production',label:'Total Production'},{field:'sale_price',label:'Total Volume'}],
  },
  {
    id:'tasks', label:'Tasks', icon:'✅', table:'tasks',
    statusField:'status', nameField:'title', subField:'due_date', valueField:null,
    dateField:'due_date',
    groupByOptions:['status','priority','agent_id'],
    statusOptions:['pending','in_progress','done','cancelled'],
    extraFilters:[{field:'priority',label:'Priority'},{field:'agent_id',label:'Agent'}],
    sortOptions:[{field:'due_date',label:'Due Date'},{field:'priority',label:'Priority'},{field:'created_at',label:'Newest'}],
    displayCols:[
      {field:'title',label:'Task'},{field:'status',label:'Status'},{field:'priority',label:'Priority'},
      {field:'due_date',label:'Due Date'},{field:'agent_id',label:'Agent'},{field:'notes',label:'Notes'},
    ],
    chartFields:[{field:'status',label:'By Status'},{field:'priority',label:'By Priority'}],
    numericFields:[],
  },
  {
    id:'listings', label:'Listings', icon:'🏡', table:'listings',
    statusField:'status', nameField:'addr', subField:'city', valueField:'list_price',
    dateField:'list_date',
    groupByOptions:['status','property_type','city','agent_id'],
    statusOptions:['Active','Under Contract','Sold','Expired','Withdrawn','Coming Soon'],
    extraFilters:[{field:'property_type',label:'Property Type'},{field:'city',label:'City'},{field:'agent_id',label:'Agent'}],
    sortOptions:[{field:'list_date',label:'List Date'},{field:'list_price',label:'Price High-Low'},{field:'created_at',label:'Newest'}],
    displayCols:[
      {field:'addr',label:'Address'},{field:'city',label:'City'},{field:'status',label:'Status'},
      {field:'list_price',label:'List Price'},{field:'beds',label:'Beds'},{field:'baths',label:'Baths'},
      {field:'sqft',label:'Sq Ft'},{field:'property_type',label:'Type'},{field:'mls_number',label:'MLS#'},
      {field:'list_date',label:'List Date'},{field:'agent_id',label:'Agent'},
    ],
    chartFields:[{field:'status',label:'By Status'},{field:'property_type',label:'By Type'},{field:'city',label:'By City'}],
    numericFields:[{field:'list_price',label:'Total List Price'}],
  },
  {
    id:'calls', label:'Calls & SMS', icon:'📞', table:'calls',
    statusField:'direction', nameField:'contact_name', subField:'from_number', valueField:null,
    dateField:'called_at',
    groupByOptions:['direction','outcome','status'],
    statusOptions:['Inbound','Outbound'],
    extraFilters:[{field:'direction',label:'Direction'},{field:'outcome',label:'Outcome'}],
    sortOptions:[{field:'called_at',label:'Newest'},{field:'contact_name',label:'Contact'},{field:'duration_sec',label:'Duration'}],
    displayCols:[
      {field:'contact_name',label:'Contact'},{field:'direction',label:'Direction'},
      {field:'outcome',label:'Outcome'},{field:'duration_sec',label:'Duration'},
      {field:'called_at',label:'Date'},{field:'from_number',label:'From'},{field:'to_number',label:'To'},
    ],
    chartFields:[{field:'direction',label:'By Direction'},{field:'outcome',label:'By Outcome'}],
    numericFields:[{field:'duration_sec',label:'Total Duration (sec)'}],
  },
  {
    id:'gifts', label:'Gifts', icon:'🎁', table:'gifts',
    statusField:'order_status', nameField:'client_name', subField:'gift_type', valueField:'amount',
    dateField:'sent_date',
    groupByOptions:['order_status','gift_type','occasion'],
    statusOptions:['Pending','Ordered','Shipped','Delivered'],
    extraFilters:[{field:'gift_type',label:'Type'},{field:'occasion',label:'Occasion'}],
    sortOptions:[{field:'created_at',label:'Newest'},{field:'client_name',label:'Name'},{field:'amount',label:'Amount'}],
    displayCols:[
      {field:'client_name',label:'Client'},{field:'gift_type',label:'Type'},
      {field:'order_status',label:'Status'},{field:'amount',label:'Amount'},
      {field:'sent_date',label:'Sent'},{field:'occasion',label:'Occasion'},{field:'agent_id',label:'Agent'},
    ],
    chartFields:[{field:'order_status',label:'By Status'},{field:'gift_type',label:'By Type'},{field:'occasion',label:'By Occasion'}],
    numericFields:[{field:'amount',label:'Total Spent'}],
  },
  {
    id:'offers', label:'Offers', icon:'📝', table:'offers',
    statusField:'status', nameField:'listing_addr', subField:'client_name', valueField:'offer_price',
    dateField:'offer_date',
    groupByOptions:['status','agent_id'],
    statusOptions:['Pending','Accepted','Rejected','Countered','Withdrawn'],
    extraFilters:[{field:'agent_id',label:'Agent'}],
    sortOptions:[{field:'offer_date',label:'Newest'},{field:'offer_price',label:'Price High-Low'}],
    displayCols:[
      {field:'listing_addr',label:'Address'},{field:'status',label:'Status'},
      {field:'offer_price',label:'Offer Price'},{field:'offer_date',label:'Date'},
      {field:'client_name',label:'Client'},{field:'agent_id',label:'Agent'},
    ],
    chartFields:[{field:'status',label:'By Status'}],
    numericFields:[{field:'offer_price',label:'Total Value'}],
  },
  {
    id:'open_houses', label:'Open Houses', icon:'🚪', table:'open_houses',
    statusField:null, nameField:'listing_addr', subField:'date', valueField:null,
    dateField:'date',
    groupByOptions:['agent_id'],
    statusOptions:[],
    extraFilters:[{field:'agent_id',label:'Agent'}],
    sortOptions:[{field:'date',label:'Date'},{field:'created_at',label:'Newest'}],
    displayCols:[
      {field:'listing_addr',label:'Address'},{field:'date',label:'Date'},
      {field:'start_time',label:'Start'},{field:'end_time',label:'End'},{field:'agent_id',label:'Agent'},
    ],
    chartFields:[],
    numericFields:[],
  },
]
