-- GENERATED by scripts/generate-identifier-seed.js. Do not hand-edit.
-- Catalog version: 1
-- Additive and idempotent: existing labels and semantic settings are preserved.

begin;

insert into public.workflow_definitions(code, entity_type_code, label)
select 'deal.lifecycle', 'deal', 'Deal Stage'
where not exists (select 1 from public.workflow_definitions where organization_id is null and code = 'deal.lifecycle');

insert into public.workflow_states(
  workflow_id, code, label, color, sort_order, semantic_type,
  is_initial, is_terminal, counts_as_active, counts_as_won
)
select w.id, 'negotiations', 'Negotiations', '#037f4c', 0, 'open',
  true, false, true, false
from public.workflow_definitions w
where w.organization_id is null and w.code = 'deal.lifecycle'
  and not exists (select 1 from public.workflow_states s where s.workflow_id = w.id and s.code = 'negotiations');

insert into public.workflow_state_aliases(workflow_state_id, alias, source_code)
select s.id, 'Negotiations', 'legacy'
from public.workflow_states s
join public.workflow_definitions w on w.id = s.workflow_id
where w.organization_id is null and w.code = 'deal.lifecycle' and s.code = 'negotiations'
  and not exists (select 1 from public.workflow_state_aliases a where a.workflow_state_id = s.id and a.source_code = 'legacy' and lower(btrim(a.alias)) = lower(btrim('Negotiations')));

insert into public.workflow_states(
  workflow_id, code, label, color, sort_order, semantic_type,
  is_initial, is_terminal, counts_as_active, counts_as_won
)
select w.id, 'offer_accepted', 'Offer Accepted', '#00c875', 1, 'open',
  false, false, true, false
from public.workflow_definitions w
where w.organization_id is null and w.code = 'deal.lifecycle'
  and not exists (select 1 from public.workflow_states s where s.workflow_id = w.id and s.code = 'offer_accepted');

insert into public.workflow_state_aliases(workflow_state_id, alias, source_code)
select s.id, 'Offer Accapted', 'legacy'
from public.workflow_states s
join public.workflow_definitions w on w.id = s.workflow_id
where w.organization_id is null and w.code = 'deal.lifecycle' and s.code = 'offer_accepted'
  and not exists (select 1 from public.workflow_state_aliases a where a.workflow_state_id = s.id and a.source_code = 'legacy' and lower(btrim(a.alias)) = lower(btrim('Offer Accapted')));

insert into public.workflow_state_aliases(workflow_state_id, alias, source_code)
select s.id, 'Offer Accepted', 'legacy'
from public.workflow_states s
join public.workflow_definitions w on w.id = s.workflow_id
where w.organization_id is null and w.code = 'deal.lifecycle' and s.code = 'offer_accepted'
  and not exists (select 1 from public.workflow_state_aliases a where a.workflow_state_id = s.id and a.source_code = 'legacy' and lower(btrim(a.alias)) = lower(btrim('Offer Accepted')));

insert into public.workflow_states(
  workflow_id, code, label, color, sort_order, semantic_type,
  is_initial, is_terminal, counts_as_active, counts_as_won
)
select w.id, 'under_shtar', 'Under Shtar', '#bb3354', 2, 'open',
  false, false, true, false
from public.workflow_definitions w
where w.organization_id is null and w.code = 'deal.lifecycle'
  and not exists (select 1 from public.workflow_states s where s.workflow_id = w.id and s.code = 'under_shtar');

insert into public.workflow_state_aliases(workflow_state_id, alias, source_code)
select s.id, 'Under Shtar', 'legacy'
from public.workflow_states s
join public.workflow_definitions w on w.id = s.workflow_id
where w.organization_id is null and w.code = 'deal.lifecycle' and s.code = 'under_shtar'
  and not exists (select 1 from public.workflow_state_aliases a where a.workflow_state_id = s.id and a.source_code = 'legacy' and lower(btrim(a.alias)) = lower(btrim('Under Shtar')));

insert into public.workflow_states(
  workflow_id, code, label, color, sort_order, semantic_type,
  is_initial, is_terminal, counts_as_active, counts_as_won
)
select w.id, 'under_contract', 'Under Contract', '#757575', 3, 'open',
  false, false, true, false
from public.workflow_definitions w
where w.organization_id is null and w.code = 'deal.lifecycle'
  and not exists (select 1 from public.workflow_states s where s.workflow_id = w.id and s.code = 'under_contract');

insert into public.workflow_state_aliases(workflow_state_id, alias, source_code)
select s.id, 'Under Contract', 'legacy'
from public.workflow_states s
join public.workflow_definitions w on w.id = s.workflow_id
where w.organization_id is null and w.code = 'deal.lifecycle' and s.code = 'under_contract'
  and not exists (select 1 from public.workflow_state_aliases a where a.workflow_state_id = s.id and a.source_code = 'legacy' and lower(btrim(a.alias)) = lower(btrim('Under Contract')));

insert into public.workflow_states(
  workflow_id, code, label, color, sort_order, semantic_type,
  is_initial, is_terminal, counts_as_active, counts_as_won
)
select w.id, 'closed', 'Closed', '#225091', 4, 'won',
  false, true, false, true
from public.workflow_definitions w
where w.organization_id is null and w.code = 'deal.lifecycle'
  and not exists (select 1 from public.workflow_states s where s.workflow_id = w.id and s.code = 'closed');

insert into public.workflow_state_aliases(workflow_state_id, alias, source_code)
select s.id, 'Closed', 'legacy'
from public.workflow_states s
join public.workflow_definitions w on w.id = s.workflow_id
where w.organization_id is null and w.code = 'deal.lifecycle' and s.code = 'closed'
  and not exists (select 1 from public.workflow_state_aliases a where a.workflow_state_id = s.id and a.source_code = 'legacy' and lower(btrim(a.alias)) = lower(btrim('Closed')));

insert into public.workflow_states(
  workflow_id, code, label, color, sort_order, semantic_type,
  is_initial, is_terminal, counts_as_active, counts_as_won
)
select w.id, 'fell_through', 'Deal Fell Through', '#ff007f', 5, 'lost',
  false, true, false, false
from public.workflow_definitions w
where w.organization_id is null and w.code = 'deal.lifecycle'
  and not exists (select 1 from public.workflow_states s where s.workflow_id = w.id and s.code = 'fell_through');

insert into public.workflow_state_aliases(workflow_state_id, alias, source_code)
select s.id, 'Deal Fell Through', 'legacy'
from public.workflow_states s
join public.workflow_definitions w on w.id = s.workflow_id
where w.organization_id is null and w.code = 'deal.lifecycle' and s.code = 'fell_through'
  and not exists (select 1 from public.workflow_state_aliases a where a.workflow_state_id = s.id and a.source_code = 'legacy' and lower(btrim(a.alias)) = lower(btrim('Deal Fell Through')));

insert into public.workflow_definitions(code, entity_type_code, label)
select 'listing.lifecycle', 'listing', 'Listing Status'
where not exists (select 1 from public.workflow_definitions where organization_id is null and code = 'listing.lifecycle');

insert into public.workflow_states(
  workflow_id, code, label, color, sort_order, semantic_type,
  is_initial, is_terminal, counts_as_active, counts_as_won
)
select w.id, 'incomplete', 'Incomplete', '#c4c4c4', 0, 'draft',
  true, false, false, false
from public.workflow_definitions w
where w.organization_id is null and w.code = 'listing.lifecycle'
  and not exists (select 1 from public.workflow_states s where s.workflow_id = w.id and s.code = 'incomplete');

insert into public.workflow_state_aliases(workflow_state_id, alias, source_code)
select s.id, 'incomplete', 'legacy'
from public.workflow_states s
join public.workflow_definitions w on w.id = s.workflow_id
where w.organization_id is null and w.code = 'listing.lifecycle' and s.code = 'incomplete'
  and not exists (select 1 from public.workflow_state_aliases a where a.workflow_state_id = s.id and a.source_code = 'legacy' and lower(btrim(a.alias)) = lower(btrim('incomplete')));

insert into public.workflow_state_aliases(workflow_state_id, alias, source_code)
select s.id, 'Incomplete', 'legacy'
from public.workflow_states s
join public.workflow_definitions w on w.id = s.workflow_id
where w.organization_id is null and w.code = 'listing.lifecycle' and s.code = 'incomplete'
  and not exists (select 1 from public.workflow_state_aliases a where a.workflow_state_id = s.id and a.source_code = 'legacy' and lower(btrim(a.alias)) = lower(btrim('Incomplete')));

insert into public.workflow_states(
  workflow_id, code, label, color, sort_order, semantic_type,
  is_initial, is_terminal, counts_as_active, counts_as_won
)
select w.id, 'coming_soon', 'Coming Soon', '#579bfc', 1, 'open',
  false, false, true, false
from public.workflow_definitions w
where w.organization_id is null and w.code = 'listing.lifecycle'
  and not exists (select 1 from public.workflow_states s where s.workflow_id = w.id and s.code = 'coming_soon');

insert into public.workflow_state_aliases(workflow_state_id, alias, source_code)
select s.id, 'Coming Soon', 'legacy'
from public.workflow_states s
join public.workflow_definitions w on w.id = s.workflow_id
where w.organization_id is null and w.code = 'listing.lifecycle' and s.code = 'coming_soon'
  and not exists (select 1 from public.workflow_state_aliases a where a.workflow_state_id = s.id and a.source_code = 'legacy' and lower(btrim(a.alias)) = lower(btrim('Coming Soon')));

insert into public.workflow_states(
  workflow_id, code, label, color, sort_order, semantic_type,
  is_initial, is_terminal, counts_as_active, counts_as_won
)
select w.id, 'active', 'Active', '#00c875', 2, 'open',
  false, false, true, false
from public.workflow_definitions w
where w.organization_id is null and w.code = 'listing.lifecycle'
  and not exists (select 1 from public.workflow_states s where s.workflow_id = w.id and s.code = 'active');

insert into public.workflow_state_aliases(workflow_state_id, alias, source_code)
select s.id, 'Active', 'legacy'
from public.workflow_states s
join public.workflow_definitions w on w.id = s.workflow_id
where w.organization_id is null and w.code = 'listing.lifecycle' and s.code = 'active'
  and not exists (select 1 from public.workflow_state_aliases a where a.workflow_state_id = s.id and a.source_code = 'legacy' and lower(btrim(a.alias)) = lower(btrim('Active')));

insert into public.workflow_states(
  workflow_id, code, label, color, sort_order, semantic_type,
  is_initial, is_terminal, counts_as_active, counts_as_won
)
select w.id, 'off_market', 'Off Market', '#fdab3d', 3, 'inactive',
  false, false, false, false
from public.workflow_definitions w
where w.organization_id is null and w.code = 'listing.lifecycle'
  and not exists (select 1 from public.workflow_states s where s.workflow_id = w.id and s.code = 'off_market');

insert into public.workflow_state_aliases(workflow_state_id, alias, source_code)
select s.id, 'Off Market', 'legacy'
from public.workflow_states s
join public.workflow_definitions w on w.id = s.workflow_id
where w.organization_id is null and w.code = 'listing.lifecycle' and s.code = 'off_market'
  and not exists (select 1 from public.workflow_state_aliases a where a.workflow_state_id = s.id and a.source_code = 'legacy' and lower(btrim(a.alias)) = lower(btrim('Off Market')));

insert into public.workflow_states(
  workflow_id, code, label, color, sort_order, semantic_type,
  is_initial, is_terminal, counts_as_active, counts_as_won
)
select w.id, 'offer_accepted', 'Accepted Offer', '#784bd1', 4, 'open',
  false, false, true, false
from public.workflow_definitions w
where w.organization_id is null and w.code = 'listing.lifecycle'
  and not exists (select 1 from public.workflow_states s where s.workflow_id = w.id and s.code = 'offer_accepted');

insert into public.workflow_state_aliases(workflow_state_id, alias, source_code)
select s.id, 'Accepted offer', 'legacy'
from public.workflow_states s
join public.workflow_definitions w on w.id = s.workflow_id
where w.organization_id is null and w.code = 'listing.lifecycle' and s.code = 'offer_accepted'
  and not exists (select 1 from public.workflow_state_aliases a where a.workflow_state_id = s.id and a.source_code = 'legacy' and lower(btrim(a.alias)) = lower(btrim('Accepted offer')));

insert into public.workflow_state_aliases(workflow_state_id, alias, source_code)
select s.id, 'Accepted Offer', 'legacy'
from public.workflow_states s
join public.workflow_definitions w on w.id = s.workflow_id
where w.organization_id is null and w.code = 'listing.lifecycle' and s.code = 'offer_accepted'
  and not exists (select 1 from public.workflow_state_aliases a where a.workflow_state_id = s.id and a.source_code = 'legacy' and lower(btrim(a.alias)) = lower(btrim('Accepted Offer')));

insert into public.workflow_states(
  workflow_id, code, label, color, sort_order, semantic_type,
  is_initial, is_terminal, counts_as_active, counts_as_won
)
select w.id, 'under_contract', 'Under Contract', '#007eb5', 5, 'open',
  false, false, true, false
from public.workflow_definitions w
where w.organization_id is null and w.code = 'listing.lifecycle'
  and not exists (select 1 from public.workflow_states s where s.workflow_id = w.id and s.code = 'under_contract');

insert into public.workflow_state_aliases(workflow_state_id, alias, source_code)
select s.id, 'Under Contract', 'legacy'
from public.workflow_states s
join public.workflow_definitions w on w.id = s.workflow_id
where w.organization_id is null and w.code = 'listing.lifecycle' and s.code = 'under_contract'
  and not exists (select 1 from public.workflow_state_aliases a where a.workflow_state_id = s.id and a.source_code = 'legacy' and lower(btrim(a.alias)) = lower(btrim('Under Contract')));

insert into public.workflow_states(
  workflow_id, code, label, color, sort_order, semantic_type,
  is_initial, is_terminal, counts_as_active, counts_as_won
)
select w.id, 'sold', 'Sold', '#ffcb00', 6, 'won',
  false, true, false, true
from public.workflow_definitions w
where w.organization_id is null and w.code = 'listing.lifecycle'
  and not exists (select 1 from public.workflow_states s where s.workflow_id = w.id and s.code = 'sold');

insert into public.workflow_state_aliases(workflow_state_id, alias, source_code)
select s.id, 'Sold', 'legacy'
from public.workflow_states s
join public.workflow_definitions w on w.id = s.workflow_id
where w.organization_id is null and w.code = 'listing.lifecycle' and s.code = 'sold'
  and not exists (select 1 from public.workflow_state_aliases a where a.workflow_state_id = s.id and a.source_code = 'legacy' and lower(btrim(a.alias)) = lower(btrim('Sold')));

insert into public.workflow_states(
  workflow_id, code, label, color, sort_order, semantic_type,
  is_initial, is_terminal, counts_as_active, counts_as_won
)
select w.id, 'expired', 'Expired', '#df2f4a', 7, 'lost',
  false, true, false, false
from public.workflow_definitions w
where w.organization_id is null and w.code = 'listing.lifecycle'
  and not exists (select 1 from public.workflow_states s where s.workflow_id = w.id and s.code = 'expired');

insert into public.workflow_state_aliases(workflow_state_id, alias, source_code)
select s.id, 'Expired', 'legacy'
from public.workflow_states s
join public.workflow_definitions w on w.id = s.workflow_id
where w.organization_id is null and w.code = 'listing.lifecycle' and s.code = 'expired'
  and not exists (select 1 from public.workflow_state_aliases a where a.workflow_state_id = s.id and a.source_code = 'legacy' and lower(btrim(a.alias)) = lower(btrim('Expired')));

insert into public.workflow_states(
  workflow_id, code, label, color, sort_order, semantic_type,
  is_initial, is_terminal, counts_as_active, counts_as_won
)
select w.id, 'withdrawn', 'Withdrawn', '#6B7280', 8, 'cancelled',
  false, true, false, false
from public.workflow_definitions w
where w.organization_id is null and w.code = 'listing.lifecycle'
  and not exists (select 1 from public.workflow_states s where s.workflow_id = w.id and s.code = 'withdrawn');

insert into public.workflow_state_aliases(workflow_state_id, alias, source_code)
select s.id, 'Withdrawn', 'legacy'
from public.workflow_states s
join public.workflow_definitions w on w.id = s.workflow_id
where w.organization_id is null and w.code = 'listing.lifecycle' and s.code = 'withdrawn'
  and not exists (select 1 from public.workflow_state_aliases a where a.workflow_state_id = s.id and a.source_code = 'legacy' and lower(btrim(a.alias)) = lower(btrim('Withdrawn')));

insert into public.workflow_state_aliases(workflow_state_id, alias, source_code)
select s.id, 'Temporary off market', 'legacy'
from public.workflow_states s
join public.workflow_definitions w on w.id = s.workflow_id
where w.organization_id is null and w.code = 'listing.lifecycle' and s.code = 'withdrawn'
  and not exists (select 1 from public.workflow_state_aliases a where a.workflow_state_id = s.id and a.source_code = 'legacy' and lower(btrim(a.alias)) = lower(btrim('Temporary off market')));

insert into public.workflow_state_aliases(workflow_state_id, alias, source_code)
select s.id, 'Seller not selling', 'legacy'
from public.workflow_states s
join public.workflow_definitions w on w.id = s.workflow_id
where w.organization_id is null and w.code = 'listing.lifecycle' and s.code = 'withdrawn'
  and not exists (select 1 from public.workflow_state_aliases a where a.workflow_state_id = s.id and a.source_code = 'legacy' and lower(btrim(a.alias)) = lower(btrim('Seller not selling')));

insert into public.workflow_definitions(code, entity_type_code, label)
select 'contact.lifecycle', 'contact', 'Contact Status'
where not exists (select 1 from public.workflow_definitions where organization_id is null and code = 'contact.lifecycle');

insert into public.workflow_states(
  workflow_id, code, label, color, sort_order, semantic_type,
  is_initial, is_terminal, counts_as_active, counts_as_won
)
select w.id, 'new', 'New', '#0EA5E9', 0, 'open',
  true, false, true, false
from public.workflow_definitions w
where w.organization_id is null and w.code = 'contact.lifecycle'
  and not exists (select 1 from public.workflow_states s where s.workflow_id = w.id and s.code = 'new');

insert into public.workflow_state_aliases(workflow_state_id, alias, source_code)
select s.id, 'New', 'legacy'
from public.workflow_states s
join public.workflow_definitions w on w.id = s.workflow_id
where w.organization_id is null and w.code = 'contact.lifecycle' and s.code = 'new'
  and not exists (select 1 from public.workflow_state_aliases a where a.workflow_state_id = s.id and a.source_code = 'legacy' and lower(btrim(a.alias)) = lower(btrim('New')));

insert into public.workflow_states(
  workflow_id, code, label, color, sort_order, semantic_type,
  is_initial, is_terminal, counts_as_active, counts_as_won
)
select w.id, 'hot', 'Hot', '#DC2626', 1, 'open',
  false, false, true, false
from public.workflow_definitions w
where w.organization_id is null and w.code = 'contact.lifecycle'
  and not exists (select 1 from public.workflow_states s where s.workflow_id = w.id and s.code = 'hot');

insert into public.workflow_state_aliases(workflow_state_id, alias, source_code)
select s.id, 'Hot', 'legacy'
from public.workflow_states s
join public.workflow_definitions w on w.id = s.workflow_id
where w.organization_id is null and w.code = 'contact.lifecycle' and s.code = 'hot'
  and not exists (select 1 from public.workflow_state_aliases a where a.workflow_state_id = s.id and a.source_code = 'legacy' and lower(btrim(a.alias)) = lower(btrim('Hot')));

insert into public.workflow_states(
  workflow_id, code, label, color, sort_order, semantic_type,
  is_initial, is_terminal, counts_as_active, counts_as_won
)
select w.id, 'warm', 'Warm', '#F97316', 2, 'open',
  false, false, true, false
from public.workflow_definitions w
where w.organization_id is null and w.code = 'contact.lifecycle'
  and not exists (select 1 from public.workflow_states s where s.workflow_id = w.id and s.code = 'warm');

insert into public.workflow_state_aliases(workflow_state_id, alias, source_code)
select s.id, 'Warm', 'legacy'
from public.workflow_states s
join public.workflow_definitions w on w.id = s.workflow_id
where w.organization_id is null and w.code = 'contact.lifecycle' and s.code = 'warm'
  and not exists (select 1 from public.workflow_state_aliases a where a.workflow_state_id = s.id and a.source_code = 'legacy' and lower(btrim(a.alias)) = lower(btrim('Warm')));

insert into public.workflow_states(
  workflow_id, code, label, color, sort_order, semantic_type,
  is_initial, is_terminal, counts_as_active, counts_as_won
)
select w.id, 'cold', 'Cold', '#94A3B8', 3, 'open',
  false, false, true, false
from public.workflow_definitions w
where w.organization_id is null and w.code = 'contact.lifecycle'
  and not exists (select 1 from public.workflow_states s where s.workflow_id = w.id and s.code = 'cold');

insert into public.workflow_state_aliases(workflow_state_id, alias, source_code)
select s.id, 'Cold', 'legacy'
from public.workflow_states s
join public.workflow_definitions w on w.id = s.workflow_id
where w.organization_id is null and w.code = 'contact.lifecycle' and s.code = 'cold'
  and not exists (select 1 from public.workflow_state_aliases a where a.workflow_state_id = s.id and a.source_code = 'legacy' and lower(btrim(a.alias)) = lower(btrim('Cold')));

insert into public.workflow_states(
  workflow_id, code, label, color, sort_order, semantic_type,
  is_initial, is_terminal, counts_as_active, counts_as_won
)
select w.id, 'active', 'Active', '#10B981', 4, 'open',
  false, false, true, false
from public.workflow_definitions w
where w.organization_id is null and w.code = 'contact.lifecycle'
  and not exists (select 1 from public.workflow_states s where s.workflow_id = w.id and s.code = 'active');

insert into public.workflow_state_aliases(workflow_state_id, alias, source_code)
select s.id, 'Active', 'legacy'
from public.workflow_states s
join public.workflow_definitions w on w.id = s.workflow_id
where w.organization_id is null and w.code = 'contact.lifecycle' and s.code = 'active'
  and not exists (select 1 from public.workflow_state_aliases a where a.workflow_state_id = s.id and a.source_code = 'legacy' and lower(btrim(a.alias)) = lower(btrim('Active')));

insert into public.workflow_states(
  workflow_id, code, label, color, sort_order, semantic_type,
  is_initial, is_terminal, counts_as_active, counts_as_won
)
select w.id, 'nurturing', 'Nurturing', '#8B5CF6', 5, 'open',
  false, false, true, false
from public.workflow_definitions w
where w.organization_id is null and w.code = 'contact.lifecycle'
  and not exists (select 1 from public.workflow_states s where s.workflow_id = w.id and s.code = 'nurturing');

insert into public.workflow_state_aliases(workflow_state_id, alias, source_code)
select s.id, 'Nurturing', 'legacy'
from public.workflow_states s
join public.workflow_definitions w on w.id = s.workflow_id
where w.organization_id is null and w.code = 'contact.lifecycle' and s.code = 'nurturing'
  and not exists (select 1 from public.workflow_state_aliases a where a.workflow_state_id = s.id and a.source_code = 'legacy' and lower(btrim(a.alias)) = lower(btrim('Nurturing')));

insert into public.workflow_states(
  workflow_id, code, label, color, sort_order, semantic_type,
  is_initial, is_terminal, counts_as_active, counts_as_won
)
select w.id, 'under_contract', 'Under Contract', '#F5A623', 6, 'open',
  false, false, true, false
from public.workflow_definitions w
where w.organization_id is null and w.code = 'contact.lifecycle'
  and not exists (select 1 from public.workflow_states s where s.workflow_id = w.id and s.code = 'under_contract');

insert into public.workflow_state_aliases(workflow_state_id, alias, source_code)
select s.id, 'Under Contract', 'legacy'
from public.workflow_states s
join public.workflow_definitions w on w.id = s.workflow_id
where w.organization_id is null and w.code = 'contact.lifecycle' and s.code = 'under_contract'
  and not exists (select 1 from public.workflow_state_aliases a where a.workflow_state_id = s.id and a.source_code = 'legacy' and lower(btrim(a.alias)) = lower(btrim('Under Contract')));

insert into public.workflow_states(
  workflow_id, code, label, color, sort_order, semantic_type,
  is_initial, is_terminal, counts_as_active, counts_as_won
)
select w.id, 'closed', 'Closed', '#225091', 7, 'completed',
  false, true, false, false
from public.workflow_definitions w
where w.organization_id is null and w.code = 'contact.lifecycle'
  and not exists (select 1 from public.workflow_states s where s.workflow_id = w.id and s.code = 'closed');

insert into public.workflow_state_aliases(workflow_state_id, alias, source_code)
select s.id, 'Closed', 'legacy'
from public.workflow_states s
join public.workflow_definitions w on w.id = s.workflow_id
where w.organization_id is null and w.code = 'contact.lifecycle' and s.code = 'closed'
  and not exists (select 1 from public.workflow_state_aliases a where a.workflow_state_id = s.id and a.source_code = 'legacy' and lower(btrim(a.alias)) = lower(btrim('Closed')));

insert into public.workflow_state_aliases(workflow_state_id, alias, source_code)
select s.id, 'Past Client', 'legacy'
from public.workflow_states s
join public.workflow_definitions w on w.id = s.workflow_id
where w.organization_id is null and w.code = 'contact.lifecycle' and s.code = 'closed'
  and not exists (select 1 from public.workflow_state_aliases a where a.workflow_state_id = s.id and a.source_code = 'legacy' and lower(btrim(a.alias)) = lower(btrim('Past Client')));

insert into public.workflow_state_aliases(workflow_state_id, alias, source_code)
select s.id, 'Client', 'legacy'
from public.workflow_states s
join public.workflow_definitions w on w.id = s.workflow_id
where w.organization_id is null and w.code = 'contact.lifecycle' and s.code = 'closed'
  and not exists (select 1 from public.workflow_state_aliases a where a.workflow_state_id = s.id and a.source_code = 'legacy' and lower(btrim(a.alias)) = lower(btrim('Client')));

insert into public.workflow_states(
  workflow_id, code, label, color, sort_order, semantic_type,
  is_initial, is_terminal, counts_as_active, counts_as_won
)
select w.id, 'unresponsive', 'Unresponsive', '#6B7280', 8, 'inactive',
  false, false, false, false
from public.workflow_definitions w
where w.organization_id is null and w.code = 'contact.lifecycle'
  and not exists (select 1 from public.workflow_states s where s.workflow_id = w.id and s.code = 'unresponsive');

insert into public.workflow_state_aliases(workflow_state_id, alias, source_code)
select s.id, 'Unresponsive', 'legacy'
from public.workflow_states s
join public.workflow_definitions w on w.id = s.workflow_id
where w.organization_id is null and w.code = 'contact.lifecycle' and s.code = 'unresponsive'
  and not exists (select 1 from public.workflow_state_aliases a where a.workflow_state_id = s.id and a.source_code = 'legacy' and lower(btrim(a.alias)) = lower(btrim('Unresponsive')));

insert into public.workflow_state_aliases(workflow_state_id, alias, source_code)
select s.id, 'Do Not Contact', 'legacy'
from public.workflow_states s
join public.workflow_definitions w on w.id = s.workflow_id
where w.organization_id is null and w.code = 'contact.lifecycle' and s.code = 'unresponsive'
  and not exists (select 1 from public.workflow_state_aliases a where a.workflow_state_id = s.id and a.source_code = 'legacy' and lower(btrim(a.alias)) = lower(btrim('Do Not Contact')));

insert into public.workflow_definitions(code, entity_type_code, label)
select 'task.lifecycle', 'task', 'Task Status'
where not exists (select 1 from public.workflow_definitions where organization_id is null and code = 'task.lifecycle');

insert into public.workflow_states(
  workflow_id, code, label, color, sort_order, semantic_type,
  is_initial, is_terminal, counts_as_active, counts_as_won
)
select w.id, 'pending', 'Pending', '#F97316', 0, 'open',
  true, false, true, false
from public.workflow_definitions w
where w.organization_id is null and w.code = 'task.lifecycle'
  and not exists (select 1 from public.workflow_states s where s.workflow_id = w.id and s.code = 'pending');

insert into public.workflow_state_aliases(workflow_state_id, alias, source_code)
select s.id, 'pending', 'legacy'
from public.workflow_states s
join public.workflow_definitions w on w.id = s.workflow_id
where w.organization_id is null and w.code = 'task.lifecycle' and s.code = 'pending'
  and not exists (select 1 from public.workflow_state_aliases a where a.workflow_state_id = s.id and a.source_code = 'legacy' and lower(btrim(a.alias)) = lower(btrim('pending')));

insert into public.workflow_state_aliases(workflow_state_id, alias, source_code)
select s.id, 'Pending', 'legacy'
from public.workflow_states s
join public.workflow_definitions w on w.id = s.workflow_id
where w.organization_id is null and w.code = 'task.lifecycle' and s.code = 'pending'
  and not exists (select 1 from public.workflow_state_aliases a where a.workflow_state_id = s.id and a.source_code = 'legacy' and lower(btrim(a.alias)) = lower(btrim('Pending')));

insert into public.workflow_state_aliases(workflow_state_id, alias, source_code)
select s.id, 'open', 'legacy'
from public.workflow_states s
join public.workflow_definitions w on w.id = s.workflow_id
where w.organization_id is null and w.code = 'task.lifecycle' and s.code = 'pending'
  and not exists (select 1 from public.workflow_state_aliases a where a.workflow_state_id = s.id and a.source_code = 'legacy' and lower(btrim(a.alias)) = lower(btrim('open')));

insert into public.workflow_states(
  workflow_id, code, label, color, sort_order, semantic_type,
  is_initial, is_terminal, counts_as_active, counts_as_won
)
select w.id, 'in_progress', 'In Progress', '#3B82F6', 1, 'open',
  false, false, true, false
from public.workflow_definitions w
where w.organization_id is null and w.code = 'task.lifecycle'
  and not exists (select 1 from public.workflow_states s where s.workflow_id = w.id and s.code = 'in_progress');

insert into public.workflow_state_aliases(workflow_state_id, alias, source_code)
select s.id, 'in_progress', 'legacy'
from public.workflow_states s
join public.workflow_definitions w on w.id = s.workflow_id
where w.organization_id is null and w.code = 'task.lifecycle' and s.code = 'in_progress'
  and not exists (select 1 from public.workflow_state_aliases a where a.workflow_state_id = s.id and a.source_code = 'legacy' and lower(btrim(a.alias)) = lower(btrim('in_progress')));

insert into public.workflow_state_aliases(workflow_state_id, alias, source_code)
select s.id, 'In Progress', 'legacy'
from public.workflow_states s
join public.workflow_definitions w on w.id = s.workflow_id
where w.organization_id is null and w.code = 'task.lifecycle' and s.code = 'in_progress'
  and not exists (select 1 from public.workflow_state_aliases a where a.workflow_state_id = s.id and a.source_code = 'legacy' and lower(btrim(a.alias)) = lower(btrim('In Progress')));

insert into public.workflow_states(
  workflow_id, code, label, color, sort_order, semantic_type,
  is_initial, is_terminal, counts_as_active, counts_as_won
)
select w.id, 'done', 'Done', '#10B981', 2, 'completed',
  false, true, false, false
from public.workflow_definitions w
where w.organization_id is null and w.code = 'task.lifecycle'
  and not exists (select 1 from public.workflow_states s where s.workflow_id = w.id and s.code = 'done');

insert into public.workflow_state_aliases(workflow_state_id, alias, source_code)
select s.id, 'done', 'legacy'
from public.workflow_states s
join public.workflow_definitions w on w.id = s.workflow_id
where w.organization_id is null and w.code = 'task.lifecycle' and s.code = 'done'
  and not exists (select 1 from public.workflow_state_aliases a where a.workflow_state_id = s.id and a.source_code = 'legacy' and lower(btrim(a.alias)) = lower(btrim('done')));

insert into public.workflow_state_aliases(workflow_state_id, alias, source_code)
select s.id, 'Done', 'legacy'
from public.workflow_states s
join public.workflow_definitions w on w.id = s.workflow_id
where w.organization_id is null and w.code = 'task.lifecycle' and s.code = 'done'
  and not exists (select 1 from public.workflow_state_aliases a where a.workflow_state_id = s.id and a.source_code = 'legacy' and lower(btrim(a.alias)) = lower(btrim('Done')));

insert into public.workflow_state_aliases(workflow_state_id, alias, source_code)
select s.id, 'completed', 'legacy'
from public.workflow_states s
join public.workflow_definitions w on w.id = s.workflow_id
where w.organization_id is null and w.code = 'task.lifecycle' and s.code = 'done'
  and not exists (select 1 from public.workflow_state_aliases a where a.workflow_state_id = s.id and a.source_code = 'legacy' and lower(btrim(a.alias)) = lower(btrim('completed')));

insert into public.workflow_state_aliases(workflow_state_id, alias, source_code)
select s.id, 'Completed', 'legacy'
from public.workflow_states s
join public.workflow_definitions w on w.id = s.workflow_id
where w.organization_id is null and w.code = 'task.lifecycle' and s.code = 'done'
  and not exists (select 1 from public.workflow_state_aliases a where a.workflow_state_id = s.id and a.source_code = 'legacy' and lower(btrim(a.alias)) = lower(btrim('Completed')));

insert into public.workflow_states(
  workflow_id, code, label, color, sort_order, semantic_type,
  is_initial, is_terminal, counts_as_active, counts_as_won
)
select w.id, 'cancelled', 'Cancelled', '#94A3B8', 3, 'cancelled',
  false, true, false, false
from public.workflow_definitions w
where w.organization_id is null and w.code = 'task.lifecycle'
  and not exists (select 1 from public.workflow_states s where s.workflow_id = w.id and s.code = 'cancelled');

insert into public.workflow_state_aliases(workflow_state_id, alias, source_code)
select s.id, 'cancelled', 'legacy'
from public.workflow_states s
join public.workflow_definitions w on w.id = s.workflow_id
where w.organization_id is null and w.code = 'task.lifecycle' and s.code = 'cancelled'
  and not exists (select 1 from public.workflow_state_aliases a where a.workflow_state_id = s.id and a.source_code = 'legacy' and lower(btrim(a.alias)) = lower(btrim('cancelled')));

insert into public.workflow_state_aliases(workflow_state_id, alias, source_code)
select s.id, 'Cancelled', 'legacy'
from public.workflow_states s
join public.workflow_definitions w on w.id = s.workflow_id
where w.organization_id is null and w.code = 'task.lifecycle' and s.code = 'cancelled'
  and not exists (select 1 from public.workflow_state_aliases a where a.workflow_state_id = s.id and a.source_code = 'legacy' and lower(btrim(a.alias)) = lower(btrim('Cancelled')));

insert into public.workflow_state_aliases(workflow_state_id, alias, source_code)
select s.id, 'canceled', 'legacy'
from public.workflow_states s
join public.workflow_definitions w on w.id = s.workflow_id
where w.organization_id is null and w.code = 'task.lifecycle' and s.code = 'cancelled'
  and not exists (select 1 from public.workflow_state_aliases a where a.workflow_state_id = s.id and a.source_code = 'legacy' and lower(btrim(a.alias)) = lower(btrim('canceled')));

insert into public.workflow_state_aliases(workflow_state_id, alias, source_code)
select s.id, 'Canceled', 'legacy'
from public.workflow_states s
join public.workflow_definitions w on w.id = s.workflow_id
where w.organization_id is null and w.code = 'task.lifecycle' and s.code = 'cancelled'
  and not exists (select 1 from public.workflow_state_aliases a where a.workflow_state_id = s.id and a.source_code = 'legacy' and lower(btrim(a.alias)) = lower(btrim('Canceled')));

insert into public.workflow_definitions(code, entity_type_code, label)
select 'offer.lifecycle', 'offer', 'Offer Status'
where not exists (select 1 from public.workflow_definitions where organization_id is null and code = 'offer.lifecycle');

insert into public.workflow_states(
  workflow_id, code, label, color, sort_order, semantic_type,
  is_initial, is_terminal, counts_as_active, counts_as_won
)
select w.id, 'draft', 'Draft', '#94A3B8', 0, 'draft',
  true, false, true, false
from public.workflow_definitions w
where w.organization_id is null and w.code = 'offer.lifecycle'
  and not exists (select 1 from public.workflow_states s where s.workflow_id = w.id and s.code = 'draft');

insert into public.workflow_state_aliases(workflow_state_id, alias, source_code)
select s.id, 'Draft', 'legacy'
from public.workflow_states s
join public.workflow_definitions w on w.id = s.workflow_id
where w.organization_id is null and w.code = 'offer.lifecycle' and s.code = 'draft'
  and not exists (select 1 from public.workflow_state_aliases a where a.workflow_state_id = s.id and a.source_code = 'legacy' and lower(btrim(a.alias)) = lower(btrim('Draft')));

insert into public.workflow_states(
  workflow_id, code, label, color, sort_order, semantic_type,
  is_initial, is_terminal, counts_as_active, counts_as_won
)
select w.id, 'sent', 'Sent', '#fdab3d', 1, 'open',
  false, false, true, false
from public.workflow_definitions w
where w.organization_id is null and w.code = 'offer.lifecycle'
  and not exists (select 1 from public.workflow_states s where s.workflow_id = w.id and s.code = 'sent');

insert into public.workflow_state_aliases(workflow_state_id, alias, source_code)
select s.id, 'Sent', 'legacy'
from public.workflow_states s
join public.workflow_definitions w on w.id = s.workflow_id
where w.organization_id is null and w.code = 'offer.lifecycle' and s.code = 'sent'
  and not exists (select 1 from public.workflow_state_aliases a where a.workflow_state_id = s.id and a.source_code = 'legacy' and lower(btrim(a.alias)) = lower(btrim('Sent')));

insert into public.workflow_states(
  workflow_id, code, label, color, sort_order, semantic_type,
  is_initial, is_terminal, counts_as_active, counts_as_won
)
select w.id, 'negotiating', 'Negotiating', '#df2f4a', 2, 'open',
  false, false, true, false
from public.workflow_definitions w
where w.organization_id is null and w.code = 'offer.lifecycle'
  and not exists (select 1 from public.workflow_states s where s.workflow_id = w.id and s.code = 'negotiating');

insert into public.workflow_state_aliases(workflow_state_id, alias, source_code)
select s.id, 'Negotiating', 'legacy'
from public.workflow_states s
join public.workflow_definitions w on w.id = s.workflow_id
where w.organization_id is null and w.code = 'offer.lifecycle' and s.code = 'negotiating'
  and not exists (select 1 from public.workflow_state_aliases a where a.workflow_state_id = s.id and a.source_code = 'legacy' and lower(btrim(a.alias)) = lower(btrim('Negotiating')));

insert into public.workflow_state_aliases(workflow_state_id, alias, source_code)
select s.id, 'Stuck', 'legacy'
from public.workflow_states s
join public.workflow_definitions w on w.id = s.workflow_id
where w.organization_id is null and w.code = 'offer.lifecycle' and s.code = 'negotiating'
  and not exists (select 1 from public.workflow_state_aliases a where a.workflow_state_id = s.id and a.source_code = 'legacy' and lower(btrim(a.alias)) = lower(btrim('Stuck')));

insert into public.workflow_states(
  workflow_id, code, label, color, sort_order, semantic_type,
  is_initial, is_terminal, counts_as_active, counts_as_won
)
select w.id, 'accepted', 'Accepted', '#00c875', 3, 'won',
  false, true, false, true
from public.workflow_definitions w
where w.organization_id is null and w.code = 'offer.lifecycle'
  and not exists (select 1 from public.workflow_states s where s.workflow_id = w.id and s.code = 'accepted');

insert into public.workflow_state_aliases(workflow_state_id, alias, source_code)
select s.id, 'Accepted', 'legacy'
from public.workflow_states s
join public.workflow_definitions w on w.id = s.workflow_id
where w.organization_id is null and w.code = 'offer.lifecycle' and s.code = 'accepted'
  and not exists (select 1 from public.workflow_state_aliases a where a.workflow_state_id = s.id and a.source_code = 'legacy' and lower(btrim(a.alias)) = lower(btrim('Accepted')));

insert into public.workflow_state_aliases(workflow_state_id, alias, source_code)
select s.id, 'AO', 'legacy'
from public.workflow_states s
join public.workflow_definitions w on w.id = s.workflow_id
where w.organization_id is null and w.code = 'offer.lifecycle' and s.code = 'accepted'
  and not exists (select 1 from public.workflow_state_aliases a where a.workflow_state_id = s.id and a.source_code = 'legacy' and lower(btrim(a.alias)) = lower(btrim('AO')));

insert into public.workflow_state_aliases(workflow_state_id, alias, source_code)
select s.id, 'Closed', 'legacy'
from public.workflow_states s
join public.workflow_definitions w on w.id = s.workflow_id
where w.organization_id is null and w.code = 'offer.lifecycle' and s.code = 'accepted'
  and not exists (select 1 from public.workflow_state_aliases a where a.workflow_state_id = s.id and a.source_code = 'legacy' and lower(btrim(a.alias)) = lower(btrim('Closed')));

insert into public.workflow_states(
  workflow_id, code, label, color, sort_order, semantic_type,
  is_initial, is_terminal, counts_as_active, counts_as_won
)
select w.id, 'rejected', 'Rejected', '#DC2626', 4, 'lost',
  false, true, false, false
from public.workflow_definitions w
where w.organization_id is null and w.code = 'offer.lifecycle'
  and not exists (select 1 from public.workflow_states s where s.workflow_id = w.id and s.code = 'rejected');

insert into public.workflow_state_aliases(workflow_state_id, alias, source_code)
select s.id, 'Rejected', 'legacy'
from public.workflow_states s
join public.workflow_definitions w on w.id = s.workflow_id
where w.organization_id is null and w.code = 'offer.lifecycle' and s.code = 'rejected'
  and not exists (select 1 from public.workflow_state_aliases a where a.workflow_state_id = s.id and a.source_code = 'legacy' and lower(btrim(a.alias)) = lower(btrim('Rejected')));

insert into public.workflow_state_aliases(workflow_state_id, alias, source_code)
select s.id, 'Fell through', 'legacy'
from public.workflow_states s
join public.workflow_definitions w on w.id = s.workflow_id
where w.organization_id is null and w.code = 'offer.lifecycle' and s.code = 'rejected'
  and not exists (select 1 from public.workflow_state_aliases a where a.workflow_state_id = s.id and a.source_code = 'legacy' and lower(btrim(a.alias)) = lower(btrim('Fell through')));

insert into public.workflow_states(
  workflow_id, code, label, color, sort_order, semantic_type,
  is_initial, is_terminal, counts_as_active, counts_as_won
)
select w.id, 'withdrawn', 'Withdrawn', '#6B7280', 5, 'cancelled',
  false, true, false, false
from public.workflow_definitions w
where w.organization_id is null and w.code = 'offer.lifecycle'
  and not exists (select 1 from public.workflow_states s where s.workflow_id = w.id and s.code = 'withdrawn');

insert into public.workflow_state_aliases(workflow_state_id, alias, source_code)
select s.id, 'Withdrawn', 'legacy'
from public.workflow_states s
join public.workflow_definitions w on w.id = s.workflow_id
where w.organization_id is null and w.code = 'offer.lifecycle' and s.code = 'withdrawn'
  and not exists (select 1 from public.workflow_state_aliases a where a.workflow_state_id = s.id and a.source_code = 'legacy' and lower(btrim(a.alias)) = lower(btrim('Withdrawn')));

insert into public.workflow_states(
  workflow_id, code, label, color, sort_order, semantic_type,
  is_initial, is_terminal, counts_as_active, counts_as_won
)
select w.id, 'expired', 'Expired', '#78716C', 6, 'lost',
  false, true, false, false
from public.workflow_definitions w
where w.organization_id is null and w.code = 'offer.lifecycle'
  and not exists (select 1 from public.workflow_states s where s.workflow_id = w.id and s.code = 'expired');

insert into public.workflow_state_aliases(workflow_state_id, alias, source_code)
select s.id, 'Expired', 'legacy'
from public.workflow_states s
join public.workflow_definitions w on w.id = s.workflow_id
where w.organization_id is null and w.code = 'offer.lifecycle' and s.code = 'expired'
  and not exists (select 1 from public.workflow_state_aliases a where a.workflow_state_id = s.id and a.source_code = 'legacy' and lower(btrim(a.alias)) = lower(btrim('Expired')));

insert into public.workflow_definitions(code, entity_type_code, label)
select 'tc.phase', 'transaction', 'Transaction Coordination Phase'
where not exists (select 1 from public.workflow_definitions where organization_id is null and code = 'tc.phase');

insert into public.workflow_states(
  workflow_id, code, label, color, sort_order, semantic_type,
  is_initial, is_terminal, counts_as_active, counts_as_won
)
select w.id, 'pre_listing', 'Pre-Listing', null, 0, 'open',
  true, false, true, false
from public.workflow_definitions w
where w.organization_id is null and w.code = 'tc.phase'
  and not exists (select 1 from public.workflow_states s where s.workflow_id = w.id and s.code = 'pre_listing');

insert into public.workflow_state_aliases(workflow_state_id, alias, source_code)
select s.id, 'pre_listing', 'legacy'
from public.workflow_states s
join public.workflow_definitions w on w.id = s.workflow_id
where w.organization_id is null and w.code = 'tc.phase' and s.code = 'pre_listing'
  and not exists (select 1 from public.workflow_state_aliases a where a.workflow_state_id = s.id and a.source_code = 'legacy' and lower(btrim(a.alias)) = lower(btrim('pre_listing')));

insert into public.workflow_state_aliases(workflow_state_id, alias, source_code)
select s.id, 'Pre-Listing', 'legacy'
from public.workflow_states s
join public.workflow_definitions w on w.id = s.workflow_id
where w.organization_id is null and w.code = 'tc.phase' and s.code = 'pre_listing'
  and not exists (select 1 from public.workflow_state_aliases a where a.workflow_state_id = s.id and a.source_code = 'legacy' and lower(btrim(a.alias)) = lower(btrim('Pre-Listing')));

insert into public.workflow_states(
  workflow_id, code, label, color, sort_order, semantic_type,
  is_initial, is_terminal, counts_as_active, counts_as_won
)
select w.id, 'active', 'Active Listing', null, 1, 'open',
  false, false, true, false
from public.workflow_definitions w
where w.organization_id is null and w.code = 'tc.phase'
  and not exists (select 1 from public.workflow_states s where s.workflow_id = w.id and s.code = 'active');

insert into public.workflow_state_aliases(workflow_state_id, alias, source_code)
select s.id, 'active', 'legacy'
from public.workflow_states s
join public.workflow_definitions w on w.id = s.workflow_id
where w.organization_id is null and w.code = 'tc.phase' and s.code = 'active'
  and not exists (select 1 from public.workflow_state_aliases a where a.workflow_state_id = s.id and a.source_code = 'legacy' and lower(btrim(a.alias)) = lower(btrim('active')));

insert into public.workflow_state_aliases(workflow_state_id, alias, source_code)
select s.id, 'Active', 'legacy'
from public.workflow_states s
join public.workflow_definitions w on w.id = s.workflow_id
where w.organization_id is null and w.code = 'tc.phase' and s.code = 'active'
  and not exists (select 1 from public.workflow_state_aliases a where a.workflow_state_id = s.id and a.source_code = 'legacy' and lower(btrim(a.alias)) = lower(btrim('Active')));

insert into public.workflow_states(
  workflow_id, code, label, color, sort_order, semantic_type,
  is_initial, is_terminal, counts_as_active, counts_as_won
)
select w.id, 'offer', 'Offer Accepted', null, 2, 'open',
  false, false, true, false
from public.workflow_definitions w
where w.organization_id is null and w.code = 'tc.phase'
  and not exists (select 1 from public.workflow_states s where s.workflow_id = w.id and s.code = 'offer');

insert into public.workflow_state_aliases(workflow_state_id, alias, source_code)
select s.id, 'offer', 'legacy'
from public.workflow_states s
join public.workflow_definitions w on w.id = s.workflow_id
where w.organization_id is null and w.code = 'tc.phase' and s.code = 'offer'
  and not exists (select 1 from public.workflow_state_aliases a where a.workflow_state_id = s.id and a.source_code = 'legacy' and lower(btrim(a.alias)) = lower(btrim('offer')));

insert into public.workflow_state_aliases(workflow_state_id, alias, source_code)
select s.id, 'Offer Accepted', 'legacy'
from public.workflow_states s
join public.workflow_definitions w on w.id = s.workflow_id
where w.organization_id is null and w.code = 'tc.phase' and s.code = 'offer'
  and not exists (select 1 from public.workflow_state_aliases a where a.workflow_state_id = s.id and a.source_code = 'legacy' and lower(btrim(a.alias)) = lower(btrim('Offer Accepted')));

insert into public.workflow_states(
  workflow_id, code, label, color, sort_order, semantic_type,
  is_initial, is_terminal, counts_as_active, counts_as_won
)
select w.id, 'under_contract', 'Under Contract', null, 3, 'open',
  false, false, true, false
from public.workflow_definitions w
where w.organization_id is null and w.code = 'tc.phase'
  and not exists (select 1 from public.workflow_states s where s.workflow_id = w.id and s.code = 'under_contract');

insert into public.workflow_state_aliases(workflow_state_id, alias, source_code)
select s.id, 'under_contract', 'legacy'
from public.workflow_states s
join public.workflow_definitions w on w.id = s.workflow_id
where w.organization_id is null and w.code = 'tc.phase' and s.code = 'under_contract'
  and not exists (select 1 from public.workflow_state_aliases a where a.workflow_state_id = s.id and a.source_code = 'legacy' and lower(btrim(a.alias)) = lower(btrim('under_contract')));

insert into public.workflow_state_aliases(workflow_state_id, alias, source_code)
select s.id, 'Under Contract', 'legacy'
from public.workflow_states s
join public.workflow_definitions w on w.id = s.workflow_id
where w.organization_id is null and w.code = 'tc.phase' and s.code = 'under_contract'
  and not exists (select 1 from public.workflow_state_aliases a where a.workflow_state_id = s.id and a.source_code = 'legacy' and lower(btrim(a.alias)) = lower(btrim('Under Contract')));

insert into public.workflow_states(
  workflow_id, code, label, color, sort_order, semantic_type,
  is_initial, is_terminal, counts_as_active, counts_as_won
)
select w.id, 'closed', 'Closed', null, 4, 'completed',
  false, true, false, false
from public.workflow_definitions w
where w.organization_id is null and w.code = 'tc.phase'
  and not exists (select 1 from public.workflow_states s where s.workflow_id = w.id and s.code = 'closed');

insert into public.workflow_state_aliases(workflow_state_id, alias, source_code)
select s.id, 'closed', 'legacy'
from public.workflow_states s
join public.workflow_definitions w on w.id = s.workflow_id
where w.organization_id is null and w.code = 'tc.phase' and s.code = 'closed'
  and not exists (select 1 from public.workflow_state_aliases a where a.workflow_state_id = s.id and a.source_code = 'legacy' and lower(btrim(a.alias)) = lower(btrim('closed')));

insert into public.workflow_state_aliases(workflow_state_id, alias, source_code)
select s.id, 'Closed', 'legacy'
from public.workflow_states s
join public.workflow_definitions w on w.id = s.workflow_id
where w.organization_id is null and w.code = 'tc.phase' and s.code = 'closed'
  and not exists (select 1 from public.workflow_state_aliases a where a.workflow_state_id = s.id and a.source_code = 'legacy' and lower(btrim(a.alias)) = lower(btrim('Closed')));

insert into public.choice_sets(code, label)
select 'task.priority', 'Task Priority'
where not exists (select 1 from public.choice_sets where organization_id is null and code = 'task.priority');

insert into public.choice_options(choice_set_id, code, label, color, sort_order)
select c.id, 'urgent', 'Urgent', '#DC2626', 0
from public.choice_sets c
where c.organization_id is null and c.code = 'task.priority'
  and not exists (select 1 from public.choice_options o where o.choice_set_id = c.id and o.code = 'urgent');

insert into public.choice_option_aliases(choice_option_id, alias, source_code)
select o.id, 'urgent', 'legacy'
from public.choice_options o
join public.choice_sets c on c.id = o.choice_set_id
where c.organization_id is null and c.code = 'task.priority' and o.code = 'urgent'
  and not exists (select 1 from public.choice_option_aliases a where a.choice_option_id = o.id and a.source_code = 'legacy' and lower(btrim(a.alias)) = lower(btrim('urgent')));

insert into public.choice_option_aliases(choice_option_id, alias, source_code)
select o.id, 'Urgent', 'legacy'
from public.choice_options o
join public.choice_sets c on c.id = o.choice_set_id
where c.organization_id is null and c.code = 'task.priority' and o.code = 'urgent'
  and not exists (select 1 from public.choice_option_aliases a where a.choice_option_id = o.id and a.source_code = 'legacy' and lower(btrim(a.alias)) = lower(btrim('Urgent')));

insert into public.choice_options(choice_set_id, code, label, color, sort_order)
select c.id, 'high', 'High', '#F97316', 1
from public.choice_sets c
where c.organization_id is null and c.code = 'task.priority'
  and not exists (select 1 from public.choice_options o where o.choice_set_id = c.id and o.code = 'high');

insert into public.choice_option_aliases(choice_option_id, alias, source_code)
select o.id, 'high', 'legacy'
from public.choice_options o
join public.choice_sets c on c.id = o.choice_set_id
where c.organization_id is null and c.code = 'task.priority' and o.code = 'high'
  and not exists (select 1 from public.choice_option_aliases a where a.choice_option_id = o.id and a.source_code = 'legacy' and lower(btrim(a.alias)) = lower(btrim('high')));

insert into public.choice_option_aliases(choice_option_id, alias, source_code)
select o.id, 'High', 'legacy'
from public.choice_options o
join public.choice_sets c on c.id = o.choice_set_id
where c.organization_id is null and c.code = 'task.priority' and o.code = 'high'
  and not exists (select 1 from public.choice_option_aliases a where a.choice_option_id = o.id and a.source_code = 'legacy' and lower(btrim(a.alias)) = lower(btrim('High')));

insert into public.choice_options(choice_set_id, code, label, color, sort_order)
select c.id, 'normal', 'Normal', '#3B82F6', 2
from public.choice_sets c
where c.organization_id is null and c.code = 'task.priority'
  and not exists (select 1 from public.choice_options o where o.choice_set_id = c.id and o.code = 'normal');

insert into public.choice_option_aliases(choice_option_id, alias, source_code)
select o.id, 'normal', 'legacy'
from public.choice_options o
join public.choice_sets c on c.id = o.choice_set_id
where c.organization_id is null and c.code = 'task.priority' and o.code = 'normal'
  and not exists (select 1 from public.choice_option_aliases a where a.choice_option_id = o.id and a.source_code = 'legacy' and lower(btrim(a.alias)) = lower(btrim('normal')));

insert into public.choice_option_aliases(choice_option_id, alias, source_code)
select o.id, 'Normal', 'legacy'
from public.choice_options o
join public.choice_sets c on c.id = o.choice_set_id
where c.organization_id is null and c.code = 'task.priority' and o.code = 'normal'
  and not exists (select 1 from public.choice_option_aliases a where a.choice_option_id = o.id and a.source_code = 'legacy' and lower(btrim(a.alias)) = lower(btrim('Normal')));

insert into public.choice_options(choice_set_id, code, label, color, sort_order)
select c.id, 'low', 'Low', '#94A3B8', 3
from public.choice_sets c
where c.organization_id is null and c.code = 'task.priority'
  and not exists (select 1 from public.choice_options o where o.choice_set_id = c.id and o.code = 'low');

insert into public.choice_option_aliases(choice_option_id, alias, source_code)
select o.id, 'low', 'legacy'
from public.choice_options o
join public.choice_sets c on c.id = o.choice_set_id
where c.organization_id is null and c.code = 'task.priority' and o.code = 'low'
  and not exists (select 1 from public.choice_option_aliases a where a.choice_option_id = o.id and a.source_code = 'legacy' and lower(btrim(a.alias)) = lower(btrim('low')));

insert into public.choice_option_aliases(choice_option_id, alias, source_code)
select o.id, 'Low', 'legacy'
from public.choice_options o
join public.choice_sets c on c.id = o.choice_set_id
where c.organization_id is null and c.code = 'task.priority' and o.code = 'low'
  and not exists (select 1 from public.choice_option_aliases a where a.choice_option_id = o.id and a.source_code = 'legacy' and lower(btrim(a.alias)) = lower(btrim('Low')));

insert into public.choice_sets(code, label)
select 'deal.side', 'Deal Side'
where not exists (select 1 from public.choice_sets where organization_id is null and code = 'deal.side');

insert into public.choice_options(choice_set_id, code, label, color, sort_order)
select c.id, 'buyer', 'Buyer', null, 0
from public.choice_sets c
where c.organization_id is null and c.code = 'deal.side'
  and not exists (select 1 from public.choice_options o where o.choice_set_id = c.id and o.code = 'buyer');

insert into public.choice_option_aliases(choice_option_id, alias, source_code)
select o.id, 'Buyer', 'legacy'
from public.choice_options o
join public.choice_sets c on c.id = o.choice_set_id
where c.organization_id is null and c.code = 'deal.side' and o.code = 'buyer'
  and not exists (select 1 from public.choice_option_aliases a where a.choice_option_id = o.id and a.source_code = 'legacy' and lower(btrim(a.alias)) = lower(btrim('Buyer')));

insert into public.choice_options(choice_set_id, code, label, color, sort_order)
select c.id, 'seller', 'Seller', null, 1
from public.choice_sets c
where c.organization_id is null and c.code = 'deal.side'
  and not exists (select 1 from public.choice_options o where o.choice_set_id = c.id and o.code = 'seller');

insert into public.choice_option_aliases(choice_option_id, alias, source_code)
select o.id, 'Seller', 'legacy'
from public.choice_options o
join public.choice_sets c on c.id = o.choice_set_id
where c.organization_id is null and c.code = 'deal.side' and o.code = 'seller'
  and not exists (select 1 from public.choice_option_aliases a where a.choice_option_id = o.id and a.source_code = 'legacy' and lower(btrim(a.alias)) = lower(btrim('Seller')));

insert into public.choice_options(choice_set_id, code, label, color, sort_order)
select c.id, 'listing', 'Listing', null, 2
from public.choice_sets c
where c.organization_id is null and c.code = 'deal.side'
  and not exists (select 1 from public.choice_options o where o.choice_set_id = c.id and o.code = 'listing');

insert into public.choice_option_aliases(choice_option_id, alias, source_code)
select o.id, 'Listing', 'legacy'
from public.choice_options o
join public.choice_sets c on c.id = o.choice_set_id
where c.organization_id is null and c.code = 'deal.side' and o.code = 'listing'
  and not exists (select 1 from public.choice_option_aliases a where a.choice_option_id = o.id and a.source_code = 'legacy' and lower(btrim(a.alias)) = lower(btrim('Listing')));

insert into public.choice_options(choice_set_id, code, label, color, sort_order)
select c.id, 'dual', 'Dual', null, 3
from public.choice_sets c
where c.organization_id is null and c.code = 'deal.side'
  and not exists (select 1 from public.choice_options o where o.choice_set_id = c.id and o.code = 'dual');

insert into public.choice_option_aliases(choice_option_id, alias, source_code)
select o.id, 'Dual', 'legacy'
from public.choice_options o
join public.choice_sets c on c.id = o.choice_set_id
where c.organization_id is null and c.code = 'deal.side' and o.code = 'dual'
  and not exists (select 1 from public.choice_option_aliases a where a.choice_option_id = o.id and a.source_code = 'legacy' and lower(btrim(a.alias)) = lower(btrim('Dual')));

insert into public.choice_option_aliases(choice_option_id, alias, source_code)
select o.id, 'Dual Buyer', 'legacy'
from public.choice_options o
join public.choice_sets c on c.id = o.choice_set_id
where c.organization_id is null and c.code = 'deal.side' and o.code = 'dual'
  and not exists (select 1 from public.choice_option_aliases a where a.choice_option_id = o.id and a.source_code = 'legacy' and lower(btrim(a.alias)) = lower(btrim('Dual Buyer')));

insert into public.choice_option_aliases(choice_option_id, alias, source_code)
select o.id, 'Dual Listing', 'legacy'
from public.choice_options o
join public.choice_sets c on c.id = o.choice_set_id
where c.organization_id is null and c.code = 'deal.side' and o.code = 'dual'
  and not exists (select 1 from public.choice_option_aliases a where a.choice_option_id = o.id and a.source_code = 'legacy' and lower(btrim(a.alias)) = lower(btrim('Dual Listing')));

insert into public.choice_options(choice_set_id, code, label, color, sort_order)
select c.id, 'rental', 'Rental', null, 4
from public.choice_sets c
where c.organization_id is null and c.code = 'deal.side'
  and not exists (select 1 from public.choice_options o where o.choice_set_id = c.id and o.code = 'rental');

insert into public.choice_option_aliases(choice_option_id, alias, source_code)
select o.id, 'Rental', 'legacy'
from public.choice_options o
join public.choice_sets c on c.id = o.choice_set_id
where c.organization_id is null and c.code = 'deal.side' and o.code = 'rental'
  and not exists (select 1 from public.choice_option_aliases a where a.choice_option_id = o.id and a.source_code = 'legacy' and lower(btrim(a.alias)) = lower(btrim('Rental')));

insert into public.choice_options(choice_set_id, code, label, color, sort_order)
select c.id, 'flip', 'Flip', null, 5
from public.choice_sets c
where c.organization_id is null and c.code = 'deal.side'
  and not exists (select 1 from public.choice_options o where o.choice_set_id = c.id and o.code = 'flip');

insert into public.choice_option_aliases(choice_option_id, alias, source_code)
select o.id, 'Flip', 'legacy'
from public.choice_options o
join public.choice_sets c on c.id = o.choice_set_id
where c.organization_id is null and c.code = 'deal.side' and o.code = 'flip'
  and not exists (select 1 from public.choice_option_aliases a where a.choice_option_id = o.id and a.source_code = 'legacy' and lower(btrim(a.alias)) = lower(btrim('Flip')));

insert into public.choice_sets(code, label)
select 'contact.interest', 'Interest Level'
where not exists (select 1 from public.choice_sets where organization_id is null and code = 'contact.interest');

insert into public.choice_options(choice_set_id, code, label, color, sort_order)
select c.id, 'hot', 'Hot', null, 0
from public.choice_sets c
where c.organization_id is null and c.code = 'contact.interest'
  and not exists (select 1 from public.choice_options o where o.choice_set_id = c.id and o.code = 'hot');

insert into public.choice_option_aliases(choice_option_id, alias, source_code)
select o.id, 'Hot', 'legacy'
from public.choice_options o
join public.choice_sets c on c.id = o.choice_set_id
where c.organization_id is null and c.code = 'contact.interest' and o.code = 'hot'
  and not exists (select 1 from public.choice_option_aliases a where a.choice_option_id = o.id and a.source_code = 'legacy' and lower(btrim(a.alias)) = lower(btrim('Hot')));

insert into public.choice_options(choice_set_id, code, label, color, sort_order)
select c.id, 'warm', 'Warm', null, 1
from public.choice_sets c
where c.organization_id is null and c.code = 'contact.interest'
  and not exists (select 1 from public.choice_options o where o.choice_set_id = c.id and o.code = 'warm');

insert into public.choice_option_aliases(choice_option_id, alias, source_code)
select o.id, 'Warm', 'legacy'
from public.choice_options o
join public.choice_sets c on c.id = o.choice_set_id
where c.organization_id is null and c.code = 'contact.interest' and o.code = 'warm'
  and not exists (select 1 from public.choice_option_aliases a where a.choice_option_id = o.id and a.source_code = 'legacy' and lower(btrim(a.alias)) = lower(btrim('Warm')));

insert into public.choice_options(choice_set_id, code, label, color, sort_order)
select c.id, 'cold', 'Cold', null, 2
from public.choice_sets c
where c.organization_id is null and c.code = 'contact.interest'
  and not exists (select 1 from public.choice_options o where o.choice_set_id = c.id and o.code = 'cold');

insert into public.choice_option_aliases(choice_option_id, alias, source_code)
select o.id, 'Cold', 'legacy'
from public.choice_options o
join public.choice_sets c on c.id = o.choice_set_id
where c.organization_id is null and c.code = 'contact.interest' and o.code = 'cold'
  and not exists (select 1 from public.choice_option_aliases a where a.choice_option_id = o.id and a.source_code = 'legacy' and lower(btrim(a.alias)) = lower(btrim('Cold')));

insert into public.choice_options(choice_set_id, code, label, color, sort_order)
select c.id, 'just_looking', 'Just Looking', null, 3
from public.choice_sets c
where c.organization_id is null and c.code = 'contact.interest'
  and not exists (select 1 from public.choice_options o where o.choice_set_id = c.id and o.code = 'just_looking');

insert into public.choice_option_aliases(choice_option_id, alias, source_code)
select o.id, 'Just Looking', 'legacy'
from public.choice_options o
join public.choice_sets c on c.id = o.choice_set_id
where c.organization_id is null and c.code = 'contact.interest' and o.code = 'just_looking'
  and not exists (select 1 from public.choice_option_aliases a where a.choice_option_id = o.id and a.source_code = 'legacy' and lower(btrim(a.alias)) = lower(btrim('Just Looking')));

insert into public.role_definitions(code, label)
select 'admin', 'Administrator'
where not exists (select 1 from public.role_definitions where organization_id is null and code = 'admin');

insert into public.role_definitions(code, label)
select 'secretary', 'Secretary'
where not exists (select 1 from public.role_definitions where organization_id is null and code = 'secretary');

insert into public.role_definitions(code, label)
select 'agent', 'Agent'
where not exists (select 1 from public.role_definitions where organization_id is null and code = 'agent');

insert into public.board_definitions(code, label, entity_type_code)
select 'contacts', 'Contacts', 'contact'
where not exists (select 1 from public.board_definitions where organization_id is null and code = 'contacts');

insert into public.board_definitions(code, label, entity_type_code)
select 'deals', 'Production', 'deal'
where not exists (select 1 from public.board_definitions where organization_id is null and code = 'deals');

insert into public.board_definitions(code, label, entity_type_code)
select 'listings', 'Listings', 'listing'
where not exists (select 1 from public.board_definitions where organization_id is null and code = 'listings');

insert into public.board_definitions(code, label, entity_type_code)
select 'tasks', 'Tasks', 'task'
where not exists (select 1 from public.board_definitions where organization_id is null and code = 'tasks');

insert into public.board_definitions(code, label, entity_type_code)
select 'offers', 'Offers', 'offer'
where not exists (select 1 from public.board_definitions where organization_id is null and code = 'offers');

insert into public.board_definitions(code, label, entity_type_code)
select 'transactions', 'Transaction Coordinator', 'transaction'
where not exists (select 1 from public.board_definitions where organization_id is null and code = 'transactions');

commit;
